nanostring/nanostring/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
]

nanostring/pages/urls.py
from django.urls import path

from .views import (
    test_view,
    home_page_view,
    set_categories_view,
    update_category_view,
    CategoryList,
    download_data_view,
    normal2BScanVectorized_view,
    disease2BScanVectorized_view,
    disease2bscan_update_view,
    normal2bscan_update_view,
    disease2bscan_delete_view,
    normal2bscan_delete_view,
    foss_licenses_page_view,
    cell_types_for_spatial_decon_uploader_view,
    cell_types_analysis_view,
    CellTypeList,
    SampleAnnotationList,
    update_cell_type_view,
    update_sample_annotations_view,
    messages_view,
    kidney_sample_annotations_uploader_view,
    sample_annotations_analysis_view,
    feature_annotation_analysis_view,
    upload_csvs_view,
    kidney_raw_bioProbeCountMatrix_analysis_view,
    KidneyRawTargetCountMatrix_analysis_view,
    KidneyQ3NormTargetCountMatrix_analysis_view,
    kidneyssGSEA_analysis_view,
    average_gene_expression_analysis_view,
)

app_name = 'pages'

urlpatterns = [
    path('test/', test_view),
    path('', home_page_view, name='home_page'),
    path('set-data-categories/', set_categories_view, name='set_data_categories_page'),
    path('update-data-category/<str:obj_name>', update_category_view, name='update_data_categories_page'),
    path('data-categories/', CategoryList.as_view(), name='data_categories_page'),
    path('download-data/', download_data_view, name='download_data_page'),
    path('disease2b-scan/', disease2BScanVectorized_view, name='disease2b_scan_page'),
    path('normal2b-scan/', normal2BScanVectorized_view, name='normal2b_scan_page'),
    path('edit-disease2bscan-vector/<int:scan_fid>/', disease2bscan_update_view, name='disease2bscan_update_page'),
    path('edit-normal2Bscan-vector/<int:scan_fid>/', normal2bscan_update_view, name='normal2bscan_update_page'),
    path('delete-disease2bscan-vector/<int:scan_fid>/', disease2bscan_delete_view, name='disease2bscan_delete_page'),
    path('delete-normal2Bscan-vector/<int:scan_fid>/', normal2bscan_delete_view, name='normal2bscan_delete_page'),
    path('foss-licenses/', foss_licenses_page_view, name='foss_licenses_page'),
    path('celltype-upload/', cell_types_for_spatial_decon_uploader_view, name='upload_celltype_page'),
    path('sampleannotation-upload/', kidney_sample_annotations_uploader_view, name='upload_sampleannotation_page'),
    path('cell-types-analysis/', cell_types_analysis_view, name='cell-types-analysis_page'),
    path('sample-annotations-analysis/', sample_annotations_analysis_view, name='sample_annotations_analysis_page'),
    path('messages/', messages_view, name='messages_page'),
    path('<slug:prev_name>/messages/', messages_view, name='messages_page'),
    path('cell-type-list/', CellTypeList.as_view(), name='list_cell_type_page'),
    path('update-cell-type/<slug:clusterid>/', update_cell_type_view, name='update_cell_type_page'),
    path('sample-annotation-list/', SampleAnnotationList.as_view(), name='list_sample_annotation_page'),
    path('update-sample-annotation/<int:id_value>/', update_sample_annotations_view, name='update_sample_annotation_page'),
    path('feature-annotations-analysis/', feature_annotation_analysis_view, name='feature_annotations_analysis_page'),
    path('upload-csvs/', upload_csvs_view, name='upload_csvs_page'),
    path('probe-expression-analysis/', kidney_raw_bioProbeCountMatrix_analysis_view, name='probe_expression_analysis_page'),
    path('target-expression-analysis/', KidneyRawTargetCountMatrix_analysis_view, name='target_expression_analysis_page'),
    path('normalized-expression-analysis/', KidneyQ3NormTargetCountMatrix_analysis_view, name='normalized_expression_analysis_page'),
    path('kidneyssGSEA-analysis/', kidneyssGSEA_analysis_view, name='kidneyssGSEA_analysis_page'),
    path('average-gene-expression-analysis/', average_gene_expression_analysis_view, name='average_gene_expression_analysis_page'),


]

nanostring/pages/templates/pages/KidneyssGSEA_analysis.html
{% extends 'pages/base_template.html' %}
{% load static %}
{% load humanize %}


{% block content %}
    
{% include 'pages/analysis_template.html' %}


{% endblock %}

nanostring/pages/templates/pages/analysis_template.html
{% load static %}
{% load humanize %}

{% block docmeta %}
{{ script_box_plot|safe }}
{{ script_bar_nested|safe }}
{% endblock %}

{% if csv_obj %}
    <div class="container shadow-lg rounded-lg my-sm-5 py-sm-2 bg-white">
        <div class="my-4">

            <div class="py-sm-2">
                <h3 class="text-center text-success">{{ page_name }} Analysis</h3>
                {% if search_count %}
                    <p class="text-info text-center lead">
                        Found {{ search_count|apnumber }} record{{ search_count|pluralize }}
                        spanning {{ columns_count|apnumber }} column{{ columns_count|pluralize }}
                    </p>
                {% endif %}
            </div>

            <div class="mt-sm-4 mb-sm-2 pt-sm-4">
                <form class="form-inline my-2 my-lg-0">
                    {{ search_form }}
                    <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
            
            {% if search_record_table %}
            <div class="shadow-sm table-responsive border my-sm-5 p-4" style="max-height: 80vh;">
                <p class="text-success text-center lead">Record for {{ search_value }}</p>
                {{ search_record_table|safe }}
            </div>
            {% endif %}
            

            <div class="shadow-sm table-responsive border my-sm-5 p-4">
                <p class="text-success text-center lead">DataFrame Description for {{ page_name }}</p>
                {{ data_DF_describe_table|safe }}
            </div>

            <div class="shadow-sm table-responsive border my-sm-5 p-4" style="max-height: 80vh;">
                <p class="text-success text-center lead">1st, 2nd and 3rd Quantiles for {{ page_name }}</p>
                {{ quantiles_1_2_3|safe }}
            </div>

            <div class="mt-sm-4 mb-sm-2 pt-sm-4">
                <form class="form-inline my-2 my-lg-0">
                    {{ quantile_search_form }}
                    <button class="btn btn-success my-2 my-sm-0" type="submit">Quantile Search</button>
                </form>
            </div>

            {% if quantile_search_table %}
            <div class="shadow-sm table-responsive border mb-sm-5 p-4" style="max-height: 80vh;">
                <p class="text-success text-center lead">Values at {{ quantile_search_percentage }}% Quantile for {{ page_name }}</p>
                {{ quantile_search_table|safe }}
            </div>
            {% endif %}

            <div class="col-12 my-sm-5">
                <div class="mx-auto p-sm-2" style="overflow: auto;">
                    {{ div_box_plot|safe }}
                </div>
            </div>

            <div class="col-12 my-sm-5">
                <div class="mx-auto p-sm-2" style="overflow: auto;">
                    {{ div_bar_nested|safe }}
                </div>
            </div>

            
        </div>
        
    </div>
{% else %}
    <div class="py-sm-2">
        <h3 class="text-center text-warning">No Data to display yet!</h3>
    </div>
{% endif %}

<script src="{% static 'pages/bokeh/bokeh-2.3.0.min.js' %}"></script>

nanostring/pages/templates/pages/copying_template.html
{% extends 'pages/base_template.html' %} {% load static %} {% load humanize %}
{% block content %}

{% endblock %}

nanostring/pages/templates/pages/disease2BScanVectorized.html
{% extends 'pages/base_template.html' %} {% load static %} {% load humanize %}
{% block docmeta %}
<link rel="stylesheet" type="text/css" href="{% static 'pages/css/disease2BScanVectorized.css' %}"/>
{% endblock %}
{% block content %}



<div class="container border shadow-lg my-5 pb-5 rounded-lg bg-white" style="overflow: auto">
	<h1 class="text-center text-info m-1 text-barlow-regular">Disease2BScan</h1>

	<div class="row media mx-auto">
		<div class="col pt-4 mx-1 px-0">
			<img src="{% static 'pages/pics/disease2bscan_raw.png' %}" class="align-self-center" style="width: 100%" alt="disease2bscan_raw" />
			<div class="media-body my-0 pt-0 pb-2">
				<p class="text-center text-info text-barlow-light my-0 py-0">georeferenced disease2bscan image</p>
			</div>
		</div>
		<div class="col pt-4 mx-1 px-0">
			<img src="{% static 'pages/pics/disease2bscan_singleband.png' %}" class="align-self-center" style="width: 100%" alt="disease2bscan_singleband" />
			<div class="media-body my-0 pt-0 pb-2">
				<p class="text-center text-info text-barlow-light my-0 py-0">singleband of disease2bscan image</p>
			</div>
		</div>
		<div class="col pt-4 mx-1 px-0">
			<img src="{% static 'pages/pics/disease2bscan_aoi.png' %}" class="align-self-center" style="width: 100%" alt="disease2bscan_aoi" />
			<div class="media-body my-0 pt-0 pb-2">
				<p class="text-center text-info text-barlow-light my-0 py-0">AOI singled out for disease2bscan image</p>
			</div>
		</div>
	</div>

	<div id="disease2BScan_map" class="mx-auto my-0"></div>
	<p class="text-center text-info text-barlow-light my-0 py-0">Vectorized Disease2BScan image showing generated AOIs</p>
	<div id="popup" class="ol-popup">
		<p class="ol-popup-closer font-weight-bold" id="popup-closer"></p>
		<div id="popup-content"></div>
	</div>
</div>

<script>
	const disease2BScanVectorized_geojson = '{{ disease2BScanVectorized_geojson|escapejs }}'
</script>
<script src="{% static 'pages/js/disease2BScanVectorized.js' %}"></script>


{% endblock %}

nanostring/pages/templates/pages/disease2bscan_update.html
{% extends 'pages/base_template.html' %} {% load static %} {% load humanize %} {% block content %}

<div class="container p-sm-4 mb-sm-5">
	<div class="shadow-lg rounded-lg my-sm-2 p-sm-4">
		<p class="lead mb-3">Disease2BScan Vectorized Image (FID.{{ scan_to_update.id }}) Update form</p>
		<form method="post">
			{% csrf_token %}
			<div class="row">
				{% for form in scan_update_form %}
				<div class="col-6">
					<p class="mt-0">{{ form.errors }}</p>
					<p class="mb-0">{{ form.label_tag }}</p>
					<p class="mb-2">{{ form }}</p>
				</div>
				{% endfor %}
			</div>
			<div class="my-2 p-2">
				<button class="btn btn-info" type="submit">Update</button>
				<a class="btn btn-secondary" href="{% url 'pages:disease2b_scan_page' %}">Back to Map</a>
			</div>
		</form>
	</div>
</div>

{% endblock %}

nanostring/pages/templates/pages/download_data.html
{% extends 'pages/base_template.html' %} {% load static %} {% load humanize %}
{% block content %}

<div class="container rounded-lg bg-white py-5">
  <div class="py-2 py-sm-4">
  <h3 class="text-center text-success">{{ page_name }}</h3>
    <p class="text-info lead mb-3">
      The data downloaded will be stored at:<br />
      <span class="font-weight-bold">
          {{ save_dir_path }}
      </span>
    </p>
  </div>


  <div class="mt-sm-4 mb-sm-2 pt-sm-4">
    <form class="form-inline my-2 my-lg-0">
      {{ download_form }}
      <button class="btn btn-success my-2 my-sm-0" type="submit">Download</button>
    </form>
  </div>
</div>

{% endblock %}

nanostring/pages/templates/pages/messages.html
{% extends 'pages/base_template.html' %}
{% load static %}
{% load humanize %}

{% block content %}

{% if messages %}
    <div class="container py-4 alert-info">
        {% for message in messages %}
            <h4{% if message.tags %} class="text-{{ message.tags }}"{% endif %}>{{ message|safe }}</h4>
        {% endfor %}
    </div>

{% endif %}

<div class="container my-4 d-flex justify-content-center">
    <a class="btn btn-outline-dark mx-2" href="../">
        Previous Page
    </a>
    <a class="btn btn-outline-dark mx-2" href="{% url 'pages:home_page' %}">
        Home Page
    </a>
</div>

{% endblock %}

nanostring/pages/templates/pages/normal2BScanVectorized.html
{% extends 'pages/base_template.html' %} {% load static %} {% load humanize %}
{% block docmeta %}
<link rel="stylesheet" type="text/css" href="{% static 'pages/css/normal2BScanVectorized.css' %}"/>
{% endblock %}
{% block content %}

<div class="container border shadow-lg my-5 pb-5 rounded-lg bg-white" style="overflow: auto">
	<h1 class="text-center text-info m-1 text-barlow-regular">Normal2BScan</h1>

	<div class="row media mx-auto">
		<div class="col pt-4 mx-1 px-0">
			<img src="{% static 'pages/pics/normal2bscan_raw.png' %}" class="align-self-center" style="width: 100%" alt="normal2bscan_raw" />
			<div class="media-body my-0 pt-0 pb-2">
				<p class="text-center text-info text-barlow-light my-0 py-0">georeferenced normal2bscan image</p>
			</div>
		</div>
		<div class="col pt-4 mx-1 px-0">
			<img src="{% static 'pages/pics/normal2bscan_singleband.png' %}" class="align-self-center" style="width: 100%" alt="normal2bscan_singleband" />
			<div class="media-body my-0 pt-0 pb-2">
				<p class="text-center text-info text-barlow-light my-0 py-0">singleband of normal2bscan image</p>
			</div>
		</div>
		<div class="col pt-4 mx-1 px-0">
			<img src="{% static 'pages/pics/normal2bscan_aoi.png' %}" class="align-self-center" style="width: 100%" alt="normal2bscan_aoi" />
			<div class="media-body my-0 pt-0 pb-2">
				<p class="text-center text-info text-barlow-light my-0 py-0">AOI singled out for normal2bscan image</p>
			</div>
		</div>
	</div>

	<div id="normal2BScan_map" class="mx-auto my-0"></div>
	<p class="text-center text-info text-barlow-light my-0 py-0">Vectorized normal2bscan image showing generated AOI regions</p>
	<div id="normal2Bpopup" class="normal2Bpopup_popup">
		<p id="normal2Bpopupcloser" class="normal2B_popup_closer font-weight-bold"></p>
		<div id="normal2BPopupContent"></div>
	</div>
</div>



<script>
	const normal2BScanVectorized_geojson = '{{ normal2BScanVectorized_geojson|escapejs }}'
</script>
<script src="{% static 'pages/js/normal2BScanVectorized.js' %}"></script>



{% endblock %}

nanostring/pages/templates/pages/normal2bscan_update.html
{% extends 'pages/base_template.html' %} {% load static %} {% load humanize %} {% block content %}

<div class="container p-sm-4 mb-sm-5">
	<div class="shadow-lg rounded-lg my-sm-2 p-sm-4">
		<p class="lead mb-3">Normal2BScanVectorized (FID.{{ scan_to_update.id }}) Update form</p>
		<form method="post">
			{% csrf_token %}
			<div class="row">
				{% for form in scan_update_form %}
				<div class="col-6">
					<p class="mt-0">{{ form.errors }}</p>
					<p class="mb-0">{{ form.label_tag }}</p>
					<p class="mb-2">{{ form }}</p>
				</div>
				{% endfor %}
			</div>
			<div class="my-2 p-2">
				<button class="btn btn-info" type="submit">Update</button>
				<a class="btn btn-secondary" href="{% url 'pages:normal2b_scan_page' %}">Back to Map</a>
			</div>
		</form>
	</div>
</div>

{% endblock %}

nanostring/pages/templates/pages/probe_expression_analysis.html
{% extends 'pages/base_template.html' %}
{% load static %}
{% load humanize %}

{% block docmeta %}
{{ script_box_plot|safe }}
{% endblock %}

{% block content %}
    {% if csv_obj %}
    
        <div class="container shadow-lg rounded-lg my-sm-5 py-sm-2">
            <div class="my-4">

                <div class="py-sm-2">
                    <h3 class="text-center text-success">{{ page_name }}</h3>
                    {% if search_count %}
                        <p class="text-info text-center lead">
                            Found {{ search_count|apnumber }} record{{ search_count|pluralize }}
                            spanning {{ columns_count|apnumber }} column{{ columns_count|pluralize }}
                        </p>
                    {% endif %}
                </div>

                <div class="mt-sm-4 mb-sm-2 pt-sm-4">
                    <form class="form-inline my-2 my-lg-0">
                        {{ search_form }}
                        <button class="btn btn-success my-2 my-sm-0" type="submit">Probe Search</button>
                    </form>
                </div>
                
                {% if search_record_table %}
                <div class="shadow-sm table-responsive border my-sm-5 p-4" style="max-height: 80vh;">
                    <p class="text-success text-center lead">Record for ProbeName {{ search_value }}</p>
                    {{ search_record_table|safe }}
                </div>
                {% endif %}
                

                <div class="shadow-sm table-responsive border my-sm-5 p-4">
                    <p class="text-success text-center lead">DataFrame Description for Probe Expression</p>
                    {{ data_DF_describe_table|safe }}
                </div>

                <div class="shadow-sm table-responsive border my-sm-5 p-4" style="max-height: 80vh;">
                    <p class="text-success text-center lead">1st, 2nd and 3rd Quantiles for Probe Expression</p>
                    {{ quantiles_1_2_3|safe }}
                </div>

                <div class="mt-sm-4 mb-sm-2 pt-sm-4">
                    <form class="form-inline my-2 my-lg-0">
                        {{ quantile_search_form }}
                        <button class="btn btn-success my-2 my-sm-0" type="submit">Quantile Search</button>
                    </form>
                </div>

                {% if quantile_search_table %}
                <div class="shadow-sm table-responsive border mb-sm-5 p-4" style="max-height: 80vh;">
                    <p class="text-success text-center lead">Values at {{ quantile_search_percentage }}% Quantile for Probe Expression</p>
                    {{ quantile_search_table|safe }}
                </div>
                {% endif %}

                <div class="col-12 my-sm-5">
                    <div class="mx-auto p-sm-2" style="overflow: auto;">
                        {{ div_box_plot|safe }}
                    </div>
                </div>

                
            </div>
            
        </div>
    {% else %}
        <div class="py-sm-2">
            <h3 class="text-center text-warning">No Probe Expression data to display yet!</h3>
        </div>
    {% endif %}


<script src="{% static 'pages/bokeh/bokeh-2.3.0.min.js' %}"></script>
{% endblock %}

nanostring/pages/templates/pages/sample_annotation_analysis.html
{% extends 'pages/base_template.html' %}
{% load static %}
{% load humanize %}

{% block docmeta %}
<link rel="stylesheet" type="text/css" href="{% static 'pages/css/sample_annotation_map.css' %}">
{{ script_pie_chart|safe }}
{{ script_scatter|safe }}
{{ script_star_plot|safe }}
{{ elbow_script|safe }}
{{ cluster_script|safe }}
{% endblock %}


{% block content %}
    {% if sample_annotations %}
    
        <div class="container shadow-lg rounded-lg my-sm-5 py-sm-2 bg-white">
            <div class="my-4">

                <div class="py-sm-2">
                    <h3 class="text-center text-success">{{ page_name }}</h3>
                </div>

                <div class="py-2 py-sm-4">
                    <form class="form-inline my-2 my-lg-0">
                        {{ sample_annotations_search_form }}
                        <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>

                {% if search_count %}
                <div class="container">
                    <p class="text-info lead">
                        Found {{ search_count|apnumber }} record{{ search_count|pluralize }}
                    </p>
                </div>
                {% endif %}

                <div class="shadow-sm table-responsive border my-sm-5 p-4" style="max-height: 40vh;">
                    <table class="table table-bordered table-striped">
                        <thead class="text-center text-success">
                            <tr>
                                <th>ID</th>
                                <th>Slide Name</th>
                                <th>Scan Name</th>
                                <th>ROI Label</th>
                                <th>Segment Label</th>
                                <th>Segment Display Name</th>
                                <th>AOI Surface Area</th>
                                <th>AOI Nuclei Count</th>
                                <th>ROI Coordinate X</th>
                                <th>ROI Coordinate Y</th>
                                <th>Raw Reads</th>
                                <th>Trimmed Reads</th>
                                <th>Stitched Reads</th>
                                <th>Aligned Reads</th>
                                <th>Duplicated Reads</th>
                                <th>Sequencing Saturation</th>
                                <th>UMIQ30</th>
                                <th>RTSQ30</th>
                                <th>Disease Status</th>
                                <th>Pathology</th>
                                <th>Region</th>
                                <th>LOQ</th>
                                <th>Normalization Factor</th>
                                <th>Geom</th>
                            </tr>
                        </thead>

                        <tbody>
                            
                            {% for data in sample_annotations %}
                                <tr>
                                    <td>{{ data.id }}</td>
                                    <td>{{ data.slide_name }}</td>
                                    <td>{{ data.scan_name }}</td>
                                    <td>{{ data.roi_label }}</td>
                                    <td>{{ data.segment_label }}</td>
                                    <td>{{ data.segment_display_name }}</td>
                                    <td>{{ data.aoi_surface_area }}</td>
                                    <td>{{ data.aoi_nuclei_count }}</td>
                                    <td>{{ data.roi_coordinate_x }}</td>
                                    <td>{{ data.roi_coordinate_y }}</td>
                                    <td>{{ data.raw_reads }}</td>
                                    <td>{{ data.trimmed_reads }}</td>
                                    <td>{{ data.stitched_reads }}</td>
                                    <td>{{ data.aligned_reads }}</td>
                                    <td>{{ data.duplicated_reads }}</td>
                                    <td>{{ data.sequencing_saturation }}</td>
                                    <td>{{ data.umiq_30 }}</td>
                                    <td>{{ data.rtsq_30 }}</td>
                                    <td>{{ data.disease_status }}</td>
                                    <td>{{ data.pathology }}</td>
                                    <td>{{ data.region }}</td>
                                    <td>{{ data.loq }}</td>
                                    <td>{{ data.normalization_factor }}</td>
                                    <td>{{ data.geom }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="my-4">

                <div class="shadow-sm table-responsive border my-sm-5 p-4">
                    <p class="text-success text-center lead">DataFrame Description for Sample Annotations</p>
                    {{ data_DF_describe_table|safe }}
                </div>
                

                <div class="mt-sm-4 mb-sm-2 pt-sm-4">
                    <form class="form-inline my-2 my-lg-0">
                        {{ quantile_search_form }}
                        <button class="btn btn-success my-2 my-sm-0" type="submit">Quantile Search</button>
                    </form>
                </div>

                {% if quantile_search_table %}
                <div class="shadow-sm table-responsive border mb-sm-5 p-4" style="max-height: 80vh;">
                    <p class="text-success text-center lead">Values at {{ quantile_search_percentage }}% Quantile for Sample Annotations</p>
                    {{ quantile_search_table|safe }}
                </div>
                {% endif %}


                <div class="shadow-sm table-responsive border my-sm-5 p-4">
                    <p class="text-success text-center lead">Stats Summary When Grouped by Disease Status</p>
                    {{ disease_status_group_describe_table|safe }}
                </div>


                <div class="col-sm-12 mx-auto mb-5" style="overflow: auto;">
                    <h1 class="text-center text-info lead m-1 font-weight-bolder">
                        Spatial Distribution of kidney sample annotations
                    </h1>
                    <div id="sampleannotation_map" class="w-75 mx-auto my-sm-2"></div>
                    <div id="mapcontent" class="w-75 mx-auto bg-light my-sm-2" style="min-height: 120px;"></div>
                </div>


                <div class="row my-sm-5">
                    <div class="mx-auto mb-5" style="overflow: auto;">
                        {{ div_scatter|safe }}
                    </div>
                </div>

                
                <div class="row my-sm-5">
                    <div class="mx-auto mb-5" style="overflow: auto;">
                        {{ div_pie_chart|safe }}
                    </div>
                </div>

                <div class="row my-sm-5">
                    <div class="mx-auto mb-5" style="overflow: auto;">
                        {{ div_star_plot|safe }}
                    </div>
                </div>


                <div class="row my-sm-5">
                    <div class="mx-auto mb-5" style="overflow: auto;">
                        {{ elbow_div|safe }}
                    </div>
                </div>


                <div class="container mt-sm-4 mb-sm-2 p-5 bg-white">
                    <form class="form-inline my-2 my-lg-0">
                        {{ cluster_points_form }}
                        <button class="btn btn-success my-2 my-sm-0" type="submit">Plot</button>
                    </form>

                    {% if model_summary %}
                    <div class="p-2">
                        <p class="text-info font-weight-bold">Model Summary</p>
                        {% for summary in model_summary %}
                            <p class="lead">
                                <span class="font-weight-bold">Cluster Centers: </span>{{ summary.cluster_centers }}
                            </p>
                            <p class="lead">
                                <span class="font-weight-bold">Inertia (WCSS): </span>{{ summary.inertia }}
                            </p>
                            <p class="lead">
                                <span class="font-weight-bold">No. of iterations: </span>{{ summary.iterations }}
                            </p>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>

                <div class="row my-sm-5">
                    <div class="mx-auto mb-5" style="overflow: auto;">
                        {{ cluster_div|safe }}
                    </div>
                </div>


            </div>

        </div>
    {% else %}
        <div class="container py-sm-2 bg-white">
            <h3 class="text-center text-warning">No Sample Annotations records yet!</h3>
        </div>
    {% endif %}

<script>
  const sampleAnnotationsVectorGeoson = "{{ sample_annotations_vector_geoson|escapejs }}";
</script>
<script src="{% static 'pages/js/sample_annotation_map.js' %}"></script>
<script src="{% static 'pages/bokeh/bokeh-2.3.0.min.js' %}"></script>
<script src="{% static 'pages/bokeh/bokeh-widgets-2.3.0.min.js' %}"></script>

{% endblock %}

nanostring/pages/templates/pages/update_cell_type.html
{% extends 'pages/base_template.html' %} {% load static %} {% load humanize %}
{% block content %}

<div class="container p-sm-4 mb-sm-5">
  <div class="shadow-lg rounded-lg my-sm-2 p-sm-4">
    <p class="lead mb-3">Cell Type {{ cell_type }} Update form</p>
    <form method="post">
    {% csrf_token %}
    <div class="row">
    {% for form in update_cells_type_csv_form %}
        <div class="col-6">
            <p class="mt-0">{{ form.errors }}</p>
            <p class="mb-0">{{ form.label_tag }}</p>
            <p class="mb-2">{{ form }}</p>
        </div>
    {% endfor %}
    </div>
      <button class="btn btn-info" type="submit">Update</button>
    </form>
  </div>
</div>

{% endblock %}

nanostring/pages/templates/pages/update_data_categories.html
{% extends 'pages/base_template.html' %} {% load static %} {% load humanize %}
{% block content %}

<div class="container">
  <div class="mt-sm-4 mb-sm-2 pt-sm-4">
    <form method="post">
      {% csrf_token %} {% for form in category_form %}
      <p class="text-danger">{{ form.errors }}</p>
      <p>{{ form.label_tag }}</p>
      <p>{{ form }}</p>
      {% endfor %}
      <button class="btn btn-info" type="submit">Update Category</button>
    </form>
  </div>
</div>

{% endblock %}

nanostring/pages/templates/pages/update_feature_annotation.html
{% extends 'pages/base_template.html' %} {% load static %} {% load humanize %}
{% block content %}

<div class="container p-sm-4 mb-sm-5">
  <div class="shadow-lg rounded-lg my-sm-2 p-sm-4">
    <p class="lead mb-3">Kidney Feature Annotations {{ feature_annotation.rts_id }} Update form</p>
    <form method="post">
    {% csrf_token %}
    <div class="row">
    {% for form in update_feature_annotation_form %}
        <div class="col-6">
            <p class="mt-0">{{ form.errors }}</p>
            <p class="mb-0">{{ form.label_tag }}</p>
            <p class="mb-2">{{ form }}</p>
        </div>
    {% endfor %}
    </div>
      <button class="btn btn-info" type="submit">Update</button>
    </form>
  </div>
</div>

{% endblock %}