nanostring/nanostring/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
]

nanostring/pages/urls.py
from django.urls import path

from .views import (
    test_view,
    home_page_view,
    set_categories_view,
    update_category_view,
    CategoryList,
    download_data_view,
    normal2BScanVectorized_view,
    disease2BScanVectorized_view,
    disease2bscan_update_view,
    normal2bscan_update_view,
    disease2bscan_delete_view,
    normal2bscan_delete_view,
    foss_licenses_page_view,
    cell_types_for_spatial_decon_uploader_view,
    cell_types_analysis_view,
    CellTypeList,
    SampleAnnotationList,
    update_cell_type_view,
    update_sample_annotations_view,
    messages_view,
    kidney_sample_annotations_uploader_view,
    sample_annotations_analysis_view,
    feature_annotation_analysis_view,
    upload_csvs_view,
    kidney_raw_bioProbeCountMatrix_analysis_view,
    KidneyRawTargetCountMatrix_analysis_view,
    KidneyQ3NormTargetCountMatrix_analysis_view,
    kidneyssGSEA_analysis_view,
    average_gene_expression_analysis_view,
)

app_name = 'pages'

urlpatterns = [
    path('test/', test_view),
    path('', home_page_view, name='home_page'),
    path('set-data-categories/', set_categories_view, name='set_data_categories_page'),
    path('update-data-category/<str:obj_name>', update_category_view, name='update_data_categories_page'),
    path('data-categories/', CategoryList.as_view(), name='data_categories_page'),
    path('download-data/', download_data_view, name='download_data_page'),
    path('disease2b-scan/', disease2BScanVectorized_view, name='disease2b_scan_page'),
    path('normal2b-scan/', normal2BScanVectorized_view, name='normal2b_scan_page'),
    path('edit-disease2bscan-vector/<int:scan_fid>/', disease2bscan_update_view, name='disease2bscan_update_page'),
    path('edit-normal2Bscan-vector/<int:scan_fid>/', normal2bscan_update_view, name='normal2bscan_update_page'),
    path('delete-disease2bscan-vector/<int:scan_fid>/', disease2bscan_delete_view, name='disease2bscan_delete_page'),
    path('delete-normal2Bscan-vector/<int:scan_fid>/', normal2bscan_delete_view, name='normal2bscan_delete_page'),
    path('foss-licenses/', foss_licenses_page_view, name='foss_licenses_page'),
    path('celltype-upload/', cell_types_for_spatial_decon_uploader_view, name='upload_celltype_page'),
    path('sampleannotation-upload/', kidney_sample_annotations_uploader_view, name='upload_sampleannotation_page'),
    path('cell-types-analysis/', cell_types_analysis_view, name='cell-types-analysis_page'),
    path('sample-annotations-analysis/', sample_annotations_analysis_view, name='sample_annotations_analysis_page'),
    path('messages/', messages_view, name='messages_page'),
    path('<slug:prev_name>/messages/', messages_view, name='messages_page'),
    path('cell-type-list/', CellTypeList.as_view(), name='list_cell_type_page'),
    path('update-cell-type/<slug:clusterid>/', update_cell_type_view, name='update_cell_type_page'),
    path('sample-annotation-list/', SampleAnnotationList.as_view(), name='list_sample_annotation_page'),
    path('update-sample-annotation/<int:id_value>/', update_sample_annotations_view, name='update_sample_annotation_page'),
    path('feature-annotations-analysis/', feature_annotation_analysis_view, name='feature_annotations_analysis_page'),
    path('upload-csvs/', upload_csvs_view, name='upload_csvs_page'),
    path('probe-expression-analysis/', kidney_raw_bioProbeCountMatrix_analysis_view, name='probe_expression_analysis_page'),
    path('target-expression-analysis/', KidneyRawTargetCountMatrix_analysis_view, name='target_expression_analysis_page'),
    path('normalized-expression-analysis/', KidneyQ3NormTargetCountMatrix_analysis_view, name='normalized_expression_analysis_page'),
    path('kidneyssGSEA-analysis/', kidneyssGSEA_analysis_view, name='kidneyssGSEA_analysis_page'),
    path('average-gene-expression-analysis/', average_gene_expression_analysis_view, name='average_gene_expression_analysis_page'),


]

nanostring/data/models.py
from django.contrib.gis.db import models

class Category(models.Model):
    CATEGORY_NAMES = [
        ('cell_deconvolution', 'Cell Deconvolution'),
        ('gene_set_enrichment_analysis', 'Gene Set Enrichment Analysis'),
        ('expressions', 'Expressions'),
    ]
    name = models.CharField('Name of category', max_length=100, unique=True, choices=CATEGORY_NAMES)
    description = models.CharField('Brief description about the category', max_length=125, null=True, blank=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self): return self.get_name_display()


class Kidney_Sample_Annotations(models.Model):
    slide_name = models.CharField(max_length=25, null=True, blank=True)
    scan_name = models.CharField(max_length=50, null=True, blank=True)
    roi_label = models.PositiveSmallIntegerField(null=True, blank=True)
    segment_label = models.CharField(max_length=125, null=True, blank=True)
    segment_display_name = models.CharField(max_length=250, null=True, blank=True)
    sample_id = models.CharField(max_length=125, null=True, blank=True)
    aoi_surface_area = models.FloatField(null=True, blank=True)
    aoi_nuclei_count = models.PositiveSmallIntegerField(null=True, blank=True) # Values from 0 to 32767 are safe in all databases supported by Django.
    roi_coordinate_x = models.IntegerField(null=True, blank=True) # Values from -2147483648 to 2147483647 are safe in all databases supported by Django.
    roi_coordinate_y = models.IntegerField(null=True, blank=True) # Values from -2147483648 to 2147483647 are safe in all databases supported by Django.
    raw_reads = models.IntegerField(null=True, blank=True) 
    trimmed_reads = models.IntegerField(null=True, blank=True)
    stitched_reads = models.IntegerField(null=True, blank=True)
    aligned_reads = models.IntegerField(null=True, blank=True)
    duplicated_reads = models.IntegerField(null=True, blank=True)
    sequencing_saturation = models.FloatField(null=True, blank=True)
    umiq_30 = models.FloatField(null=True, blank=True)
    rtsq_30 = models.FloatField(null=True, blank=True)
    disease_status = models.CharField(max_length=25, null=True, blank=True)
    pathology = models.CharField(max_length=25, null=True, blank=True)
    region = models.CharField(max_length=25, null=True, blank=True)
    loq = models.FloatField(null=True, blank=True)
    normalization_factor = models.FloatField(null=True, blank=True)
    geom = models.PointField(srid=3857, null=True, blank=True)


    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name="category of data"
        )

    class Meta:
        ordering = ['roi_label']
        verbose_name = 'sample annotation'
        verbose_name_plural = 'sample annotations'

    def __str__(self): return f'{self.roi_label}: {self.slide_name}'
    


class Cell_Types_for_Spatial_Decon(models.Model):
    cluster_id = models.CharField(max_length=8, null=True, blank=True)
    alias = models.CharField(max_length=8, null=True, blank=True)
    data_set = models.CharField(max_length=250, null=True, blank=True)
    number_of_cells = models.PositiveSmallIntegerField(null=True, blank=True)
    cell_type1 = models.CharField(max_length=125, null=True, blank=True)
    cell_type2 = models.CharField(max_length=125, null=True, blank=True)
    cell_type3 = models.CharField(max_length=125, null=True, blank=True)
    cell_type_specific = models.CharField(max_length=125, null=True, blank=True)
    cell_type_general = models.CharField(max_length=125, null=True, blank=True)
    cluster_name = models.CharField(max_length=125, null=True, blank=True)

    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name="category of data"
        )


    class Meta:
        ordering = ['-number_of_cells', 'cluster_id', ]
        verbose_name = 'cell type'
        verbose_name_plural = 'cell annotations (cell types)'


    def __str__(self): return self.cluster_id



class RawCSVFiles(models.Model):
    DATA_NAMES = [
        ('Kidney_Sample_Annotations.csv', 'Kidney_Sample_Annotations.csv'),
        ('Kidney_Feature_Annotations.csv', 'Kidney_Feature_Annotations.csv'),
        ('Kidney_Raw_BioProbeCountMatrix.csv', 'Kidney_Raw_BioProbeCountMatrix.csv'),
        ('Kidney_Raw_TargetCountMatrix.csv', 'Kidney_Raw_TargetCountMatrix.csv'),
        ('Kidney_Q3Norm_TargetCountMatrix.csv', 'Kidney_Q3Norm_TargetCountMatrix.csv'),
        ('Cell_Types_for_Spatial_Decon.csv', 'Cell_Types_for_Spatial_Decon.csv'),
        ('Young_kidney_cell_profile_matrix.csv', 'Young_kidney_cell_profile_matrix.csv'),
        ('Kidney_ssGSEA.csv', 'Kidney_ssGSEA.csv'),
    ]
    file_name = models.CharField(max_length=125, choices=DATA_NAMES)
    file = models.FileField(upload_to='csv_uploads/')

    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name="category of data"
    )
        

    def __str__(self): return self.file_name



class Disease2BScanVectorized(models.Model):
    fid = models.BigIntegerField()
    dn = models.BigIntegerField()
    name = models.CharField(max_length=254, null=True, blank=True)
    geom = models.MultiPolygonField(srid=3857)

    def __str__(self): return str(self.fid)



class Normal2BScanVectorized(models.Model):
    fid = models.BigIntegerField()
    dn = models.BigIntegerField()
    name = models.CharField(max_length=254, null=True, blank=True)
    geom = models.MultiPolygonField(srid=3857)

    def __str__(self): return str(self.fid)

nanostring/data/views.py
from django.shortcuts import render

nanostring/pages/templates/data/category_list.html
{% extends 'pages/base_template.html' %} {% load static %} {% load humanize %}
{% block content %}

<div class="container p-4 shadow-lg rounded-lg bg-white">
    

    <div class="container row">
    {% for item in object_list %}
        <div class="list-group my-sm-2 col-sm-4">
            <p class="font-weight-bold text-info">{{ forloop.counter }}. {{ item.get_name_display }}</p>
            <p class="text-info">{{ item.description }}</p>
            {% for spec_item in item.rawcsvfiles_set.all %}
            <div class="bg-light" style="min-height: 50px; max-height: 50px; overflow-x:scroll; overflow-y:scroll;">
                <p class="font-weight-bold text-info">{{ forloop.counter }}. {{ spec_item.name }}</p>
            </div>
            {% empty %}
                <p class="text-warning text-center">No CSVs data here yet!</p>
            {% endfor %}
            <a class="btn btn-outline-primary" href="{% url 'pages:update_data_categories_page' item.name %}">
                Edit
            </a>
        </div>
    {% empty %}
        <h2 class="text-warning">No Categories yet!</h2>
    {% endfor %}
    </div>

    <div class="w-75 mx-auto py-5">
        <a href="{% url 'pages:set_data_categories_page' %}">Add new Category</a>
    </div>
</div>

{% endblock %}

nanostring/pages/templates/data/cell_types_for_spatial_decon_list.html
{% extends 'pages/base_template.html' %} {% load static %} {% load humanize %}
{% block content %}

<div class="container p-4 shadow-lg rounded lg">
    <div class="w-75 mx-auto">
        <h2 class="text-success p-sm-4">Choose Cell Type to Update</h2>
    </div>
    {% for celltype in object_list %}
        <div class="list-group my-sm-2">
            <a href="{% url 'pages:update_cell_type_page' celltype.cluster_id %}" class="list-group-item list-group-item-action w-75 mx-auto">
                {{ celltype.cluster_id }} ({{ celltype.alias }})
            </a>
        </div>
    {% empty %}
        <h2 class="text-warning">No Cell Types yet!</h2>
    {% endfor %}
</div>

{% endblock %}

nanostring/pages/templates/data/kidney_sample_annotations_list.html
{% extends 'pages/base_template.html' %} {% load static %} {% load humanize %}
{% block content %}

<div class="container p-4 shadow-lg rounded lg">
    <div class="w-75 mx-auto">
        <h2 class="text-success p-sm-4">Choose Sample Annotation to Update</h2>
    </div>

    <div class="container row">
    {% for item in object_list %}
        <div class="list-group my-sm-2 col-sm-4">
            <a href="{% url 'pages:update_sample_annotation_page' item.slug %}" class="list-group-item list-group-item-action w-75 mx-auto">
                {{ item.slug }}
            </a>
        </div>
    {% empty %}
        <h2 class="text-warning">No Sample Annotations yet!</h2>
    {% endfor %}
    </div>
</div>

{% endblock %}